name: Run Selenium On GitHub Action

on:
  workflow_dispatch:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install package list
        run: apt list --installed    

      - name: Remove previous chrome instances on runner 
        run: sudo apt purge google-chrome-stable  
        
       # Need to fetch reqs if needed
      - name: Install all necessary packages
        run: | 
          sudo apt-get install xvfb
          pip install chromedriver-autoinstaller selenium pyvirtualdisplay
          python -m pip install --upgrade pip
          if [-f requirements.txt ]; then pip install -r requirements.txt; fi

      # - name: Install xvfb
      #   run: sudo apt-get install xvfb

      - name: Running the Python script
        run: |
          python main.py
        env:
          MY_GITHUB_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}


        
      # - name: Commit and Push The Results From Python Selenium Action
      #   run: |
      #    git config --global user.name "krooner"
      #    git config --global user.email "krooner.kim@gmail.com"
      #    git add -A
      #    git commit -m "GitHub Actions Results added"
      #    git push
